
# Syntax highlighting
markdown:            kramdown
highlighter:         pygments

# Permalinks
permalink:           /:title

# Setup
timezone:            Europe/Madrid
locale:              es_es
name:				         SAG
title:               Sergio Abreu García
tagline:             'Technology & Software'
description:         'Software developer | Portfolio & Blog'
rss_description:     'Sergio Abreu García Blog | Tech & Software'
url:                 https://sag-dev.com
rss:                 https://sag-dev.com/feed.xml
baseurl:             ''
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/featured/'
baseurl_work_img:     '/assets/images/work/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
baseurl_favicon:     '/assets/images/favicon.ico'
baseurl_favicon_png: '/assets/images/favicon.png'
defaultImg:          '/assets/images/default.jpg'
disqus:              sag-dev

author:
  name:           	 Sergio Abreu García
  url:            	 https://sag-dev.com
  email:             contact@sag-dev.com
  linkedin:          sag-dev
  github:            Sag-Dev

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml", "package-lock.json", "gulpfile.js", "miscellaneous"]
include:             ["CNAME"]
port:             	 9001

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"

collections:
  - work
