
# Syntax highlighting
markdown:            kramdown
highlighter:         pygments

# Permalinks
permalink:           /:title

# Setup
timezone:            Europe/Madrid
locale:              es_es
name:				 Artei
title:               Artei
tagline:             'La historia de la humanidad es la historia del progreso'
description:         'Blog sobre las tecnologías que dan forma al mundo'
url:                 https://sag-dev.github.io
rss:                 https://sag-dev.github.io/meigo/feed.xml
baseurl:             ''
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                assets/images/icon.png
disqus:              artei

author:
  name:           	 Sergio Abreu García
  url:            	 sag-dev.com
  twitter:           ArteiTech
  youtube:           ArteiTech
  facebook:          ArteiTech
  email:             sagdev0@gmail.com

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
