
# Syntax highlighting
markdown:            kramdown
highlighter:         pygments

# Permalinks
permalink:           /:title

# Setup
timezone:            Europe/Madrid
locale:              es_es
name:				 Artei
title:               Artei
tagline:             'La historia de la humanidad es la historia del progreso'
description:         'Artei'
url:                 sag-dev.github.io
rss:                 rss feed url
baseurl:             ''
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                assets/images/icon.png
disqus:              disqus_shortname # get it on https://disqus.com/admin/

author:
  name:           	 Sergio Abreu García
  url:            	 sag-dev.com
  facebook:          username
  twitter:           username
  linkedin:          username
  youtube:           ArteiTech

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
