# The URL the site will be built for
base_url = "https://sergioabreu.me"

# Theme name to use
theme = "hermit_zola"

# Used in RSS by default
title = "Sergio Abreu García"
description = "Software developer"
# The default language, used in RSS
default_language = "en"

# Highlight all code blocks found
# Or enable the highlight.js in the 'extra' config section
highlight_code = false

# Which theme to use for the code highlighting.
# See below for list of accepted values
highlight_theme = "agola-dark"

# Whether to generate a RSS feed automatically
generate_feed = false
feed_filename = "rss.xml"

# The number of articles to include in the RSS feed. Will include all items if
# not set (the default).
# rss_limit = 20

# The taxonomies to be rendered for that site and their configuration
# Example:
#     taxonomies = [
#       {name = "tags", rss = true}, # each tag will have its own RSS feed
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no RSS or pagination
#     ]
#
taxonomies = [
           {name = "tags", rss = true}
]

# Whether to compile the Sass files found in the `sass` directory
compile_sass = true

# Whether to build a search index out of the pages and section
# content for the `default_language`
build_search_index = false

# A list of glob patterns specifying asset files to ignore when
# processing the content directory.
# Defaults to none, which means all asset files are copied over to the public folder.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*"]
ignored_content = []

# A list of directories to search for additional `.sublime-syntax` files in.
extra_syntaxes = []

# Optional translation object. The key if present should be a language code
[translations]

# You can put any kind of data in there and it
# will be accessible in all templates

[extra]
home_subtitle = "Software developer that loves building stuff"

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
    #{ link = "/posts", name = "Posts" },
    #{ link = "/about", name = "About" }
]

hermit_social = [
    { name = "youtube", link = "https://www.youtube.com/c/sergioabreu-g" },
    { name = "github", link = "https://github.com/sergioabreu-g" },
    { name = "linkedin", link = "https://www.linkedin.com/in/sergioabreu-g/" },
    { name = "cv", link = "/Sergio%20Abreu%20García%20-%20Resume.pdf" },
    { name = "email", link = "mailto:author@domain.com" }
]



[extra.highlightjs]
enable = true
clipboard = true
theme = "vs2015"

[extra.disqus]
enable = false
# Take this from your Disqus account
shortname = "my-supa-dupa-blog"

[extra.author]
name = "Sergio Abreu García"
email = "contact@sergioabreu.me"

[extra.google_analytics]
enable = false
id = "UA-4XXXXXXX-X"
